### ISSUE TITLE
Can not connect a container to a network.

### ISSUE THREAD

**Issue by antoineVerlant** [docker/docker-py#1562] opened 2017-04-12 15:25 UTC
Hello devs,

I'm trying to create a container connected to a network using this code 
```
container = client.containers.run(
            detach=True, name=instance.name,
            image=instance.image_id.identifier,
            environment=instance.parse_environment_variable(),
            networks=instance.parse_network(),
            ports=instance.parse_port(),
            volumes=instance.parse_volume())
```
Where instance.parse_network give a list of network name ( the list with the one I test looks like that : `[u'superNetwork']` ).
Also this list works when I use it in `client.services.create(networks=list)`.
I try to connect to this network :
```
docker network inspect superNetwork
[
    {
        "Name": "superNetwork",
        "Id": "nyl28mp8by029wy8tsid0fm3a",
        "Created": "2017-04-12T14:13:28.763347709Z",
        "Scope": "swarm",
        "Driver": "overlay",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "10.0.1.0/24",
                    "Gateway": "10.0.1.1"
                }
            ]
        },
        "Internal": false,
        "Attachable": true,
        "Containers": {
            "43dd515a8b23e1667e06e49146d44c33cbd03df5662fba720a70a5ad326ada75": {
                "Name": "superServiceNetwork.1.op33udodk3ktuvaf8h50w8s5o",
                "EndpointID": "4e9a77c4f35a1079ed8cc2ade9b19c36b2d548994d99ecd8b3037ca60acbb5bd",
                "MacAddress": "02:42:0a:00:01:03",
                "IPv4Address": "10.0.1.3/24",
                "IPv6Address": ""
            }
        },
        "Options": {
            "com.docker.network.driver.overlay.vxlanid_list": "4098"
        },
        "Labels": {},
        "Peers": [
            {
                "Name": "d17cb33d234c-178b67217b77",
                "IP": "172.17.0.2"
            }
        ]
    }
]
```
I can create the container with the simple command line 
`docker run --network superNetwork image`
I try to bypass the problem with this : 
```
            for network_record in instance.network_ids:
                network = client.networks.get(network_record.identifier)
                network.connect(container)
```
But it doesn't work neither.
I didn't find any reason.
Can you help me ?
Thank you

**Comment by dacameron** [comment] 2017-04-13 07:33
You could try 
```python
client.api.connect_container_to_network(container.name, network_name)
```
which is what I did to get around this bug. I can't get 
```python
client.containers.run(networks=[network_name])
```
to work either.

**Comment by antoineVerlant** [comment] 2017-04-13 08:57
@dacameron Thanks for your answer.
In fact it looks like that the `network.connect(container)` works now, I should have did mistake while testing.
But I finally use your 
`        for network_name in instance.parse_network():
            client.api.connect_container_to_network(container.name, network_name)`
Wich is better for my code base. Thanks a lot.
But like you said, the `client.containers.run(networks=[network_name])` still doesn't work.

**Comment by anirudh-chhangani** [comment] 2017-04-26 12:23
can anyone from the core team acknowledge the issue, any timeline when this might get fixed.

**Comment by shin-** [comment] 2017-04-27 22:04
Duplicate of #1433

**Closed by shin-** 2017-04-27 22:04 UTC
