### ISSUE TITLE
[Ansible] Error: docker-py version is 1.10.1. Minimum version required is 1.7.0.

### ISSUE THREAD

**Issue by rcoh** [docker/docker-py#1200] opened 2016-09-10 00:38 UTC
```
  154         if docker_version < MIN_DOCKER_VERSION:
  155             self.fail("Error: docker-py version is %s. Minimum version required is %s." % (docker_version,
  156                                                                                            MIN_DOCKER_VERSION))
```
In python:

```
Python 2.7.11 (default, Jan 22 2016, 08:29:18) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.2 (clang-700.1.81)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> "1.5" < "1.7"
True
>>> "1.9" < "1.7"
False
>>> "1.10.1" < "1.7"
True
>>> "1.10.1" < "1.7.0"
True
>>> "1.10" < "1.7.0"
True
```

**Comment by rcoh** [comment] 2016-09-10 00:40
(Not really your fault, also filing the same issue against ansible)

**Comment by shin-** [comment] 2016-09-10 00:45
Yeah, that's on `ansible`, unfortunately. https://github.com/ansible/ansible/blob/devel/lib/ansible/module_utils/docker_common.py#L154

The docker module has had a `version_info` for a while now (since 1.2), so there's no excuse for not using it.

**Comment by shin-** [comment] 2016-09-10 00:49
I'm gonna close this since the issue is downstream, but feel free to ping me here if there's anything I can do to help.

**Closed by shin-** 2016-09-10 00:49 UTC
Labels: invalid, release-management

**Comment by rcoh** [comment] 2016-09-10 00:53
For people who found this via google:

**Temporary fix**
Downgrade to 1.9.0:
```
 roles:
    - { role: angstwad.docker_ubuntu, pip_version_docker_py: 1.9.0 }
```
