### ISSUE TITLE
docker-py build cache differs from docker build cache

### ISSUE THREAD

**Issue by seanmcl** [docker/docker-py#420] opened 2014-12-12 16:31 UTC
I build images in 2 ways:
- docker build .
- with docker-py, e.g.

``` python
import docker
client = docker.Client()
for line in client.build(path="."):
    print line
```

The caches for these two methods seem to be independent.  If I change an ADDed file, for example, and then rebuild the image using 'docker build', a subsequent build using docker-py starts from the same ADD command, rather than noticing the image is up to date.  And vice versa.

docker-py 0.6.0
docker 1.3.0

I recognize this could be a bug with docker.  If that's true, please let me know and I'll move this.

**Comment by romanlevin** [comment] 2016-06-10 09:38
Described in (much) more detail in #998.

**Comment by bfirsh** [comment] 2016-11-28 19:21
Closing as a dupe of #998.

**Closed by bfirsh** 2016-11-28 19:21 UTC
