### ISSUE TITLE
Container class "status" attr never changes

### ISSUE THREAD

**Issue by johntmyers** [docker/docker-py#2144] opened 2018-09-26 19:13 UTC
Hi, I'm running version 3.5.0 with Docker CE 18.06.1-ce-mac73 (26764). Whenever I launch a container with `detach=True`, the returned Container object will never have its `status` attr updated from `created`.

Simple example below, normally this command just takes a half-second to run or so.

```python
In [200]: def run():
     ...:     c = d.containers.run('ubuntu', 'echo hello world', detach=True)
     ...:     time.sleep(10)
     ...:     print(c.status)
     ...:
     ...:

In [201]:

In [201]: run()
created
```

**Comment by shin-** [comment] 2018-09-26 19:37
Duplicate of #1860 
Duplicate of #1985 
Duplicate of #1534

**Closed by shin-** 2018-09-26 19:37 UTC
