### ISSUE TITLE
Failed to import docker - No module named ssl_match_hostname

### ISSUE THREAD

**Issue by jean-christophe-manciot** [docker/docker-py#1962] opened 2018-03-16 14:26 UTC
##### ENVIRONMENT
* Operating System: Ubuntu 17.10
* PYTHONPATH /usr/local/lib/python2.7/dist-packages
* docker: 3.1.1 (available in $PYTHONPATH)
* backports.ssl-match-hostname: 3.5.0.1 (available in $PYTHONPATH)

##### STEPS TO REPRODUCE

```
# pip install -I docker
Collecting docker
  Using cached docker-3.1.1-py2.py3-none-any.whl
Collecting backports.ssl-match-hostname>=3.5; python_version < "3.5" (from docker)
Collecting ipaddress>=1.0.16; python_version < "3.3" (from docker)
Collecting six>=1.4.0 (from docker)
  Using cached six-1.11.0-py2.py3-none-any.whl
Collecting docker-pycreds>=0.2.2 (from docker)
  Using cached docker_pycreds-0.2.2-py2.py3-none-any.whl
Collecting requests!=2.18.0,>=2.14.2 (from docker)
  Using cached requests-2.18.4-py2.py3-none-any.whl
Collecting websocket-client>=0.32.0 (from docker)
  Using cached websocket_client-0.47.0-py2.py3-none-any.whl
Collecting certifi>=2017.4.17 (from requests!=2.18.0,>=2.14.2->docker)
  Using cached certifi-2018.1.18-py2.py3-none-any.whl
Collecting chardet<3.1.0,>=3.0.2 (from requests!=2.18.0,>=2.14.2->docker)
  Using cached chardet-3.0.4-py2.py3-none-any.whl
Collecting idna<2.7,>=2.5 (from requests!=2.18.0,>=2.14.2->docker)
  Using cached idna-2.6-py2.py3-none-any.whl
Collecting urllib3<1.23,>=1.21.1 (from requests!=2.18.0,>=2.14.2->docker)
  Using cached urllib3-1.22-py2.py3-none-any.whl
Installing collected packages: backports.ssl-match-hostname, ipaddress, six, docker-pycreds, certifi, chardet, idna, urllib3, requests, websocket-client, docker
Successfully installed backports.ssl-match-hostname-3.5.0.1 certifi-2018.1.18 chardet-3.0.4 docker-3.1.1 docker-pycreds-0.2.2 idna-2.6 ipaddress-1.0.19 requests-2.18.4 six-1.11.0 urllib3-1.22 websocket-client-0.47.0

# python2 -c "import docker"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/docker/__init__.py", line 2, in <module>
    from .api import APIClient
  File "/usr/local/lib/python2.7/dist-packages/docker/api/__init__.py", line 2, in <module>
    from .client import APIClient
  File "/usr/local/lib/python2.7/dist-packages/docker/api/client.py", line 10, in <module>
    from .build import BuildApiMixin
  File "/usr/local/lib/python2.7/dist-packages/docker/api/build.py", line 5, in <module>
    from .. import auth
  File "/usr/local/lib/python2.7/dist-packages/docker/auth.py", line 9, in <module>
    from .utils import config
  File "/usr/local/lib/python2.7/dist-packages/docker/utils/__init__.py", line 2, in <module>
    from .build import tar, exclude_paths
  File "/usr/local/lib/python2.7/dist-packages/docker/utils/build.py", line 7, in <module>
    from .utils import create_archive
  File "/usr/local/lib/python2.7/dist-packages/docker/utils/utils.py", line 16, in <module>
    from .. import tls
  File "/usr/local/lib/python2.7/dist-packages/docker/tls.py", line 5, in <module>
    from .transport import SSLAdapter
  File "/usr/local/lib/python2.7/dist-packages/docker/transport/__init__.py", line 3, in <module>
    from .ssladapter import SSLAdapter
  File "/usr/local/lib/python2.7/dist-packages/docker/transport/ssladapter.py", line 21, in <module>
    from backports.ssl_match_hostname import match_hostname
ImportError: No module named ssl_match_hostname
```
despite:
```
# pip2 freeze | grep backports
backports-abc==0.5
backports.ssl-match-hostname==3.5.0.1
```

**Comment by jean-christophe-manciot** [comment] 2018-03-16 14:32
Same issue with all docker releases between ```2.7.0``` and ```3.1.1```. I have not tested earlier versions.

**Comment by shin-** [comment] 2018-03-16 18:27
Duplicate of #1502

**Closed by shin-** 2018-03-16 18:27 UTC
