### ISSUE TITLE
SSL: CERTIFICATE_VERIFY_FAILED error with boot2docker

### ISSUE THREAD

**Issue by garethr** [docker/docker-py#465] opened 2015-01-26 11:31 UTC
Using the latest versions of docker-py and boot2docker I'm unable to make simple requests, receiving an SSL: CERTIFICATE_VERIFY_FAILED error.

Given the following test case.

```
> cat test.py
from docker.client import Client
from docker.utils import kwargs_from_env

kwargs = kwargs_from_env()

client = Client(**kwargs)
print client.version()
```

I get the following error:

```
python test.py                                                                                                                                                                                                     ~/Documents/puppet2docker
Traceback (most recent call last):
  File "test.py", line 10, in <module>
    print client.version()
  File "/Users/garethr/Documents/puppet2docker/lib/python2.7/site-packages/docker_py-0.7.1-py2.7.egg/docker/client.py", line 986, in version
    return self._result(self._get(self._url("/version")), True)
  File "/Users/garethr/Documents/puppet2docker/lib/python2.7/site-packages/docker_py-0.7.1-py2.7.egg/docker/client.py", line 81, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
  File "/Users/garethr/Documents/puppet2docker/lib/python2.7/site-packages/requests-2.4.3-py2.7.egg/requests/sessions.py", line 469, in get
    return self.request('GET', url, **kwargs)
  File "/Users/garethr/Documents/puppet2docker/lib/python2.7/site-packages/requests-2.4.3-py2.7.egg/requests/sessions.py", line 457, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/garethr/Documents/puppet2docker/lib/python2.7/site-packages/requests-2.4.3-py2.7.egg/requests/sessions.py", line 569, in send
    r = adapter.send(request, **kwargs)
  File "/Users/garethr/Documents/puppet2docker/lib/python2.7/site-packages/requests-2.4.3-py2.7.egg/requests/adapters.py", line 420, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)
```

Looking further, `kwargs_to_env` does appear to have picked everything up correctly:

```
(Pdb) kwargs['tls'].__dict__
{'assert_hostname': None, 'cert': ('/Users/garethr/.boot2docker/certs/boot2docker-vm/cert.pem', '/Users/garethr/.boot2docker/certs/boot2docker-vm/key.pem'), 'ssl_version': 5, 'verify': '/Users/garethr/.boot2docker/certs/boot2docker-vm/ca.pem'}
```

And the referenced certs exist:

```
ls /Users/garethr/.boot2docker/certs/boot2docker-vm/
ca.pem   cert.pem key.pem
```

I'm using Python 2.7.9 on OSX.

```
> python --version
Python 2.7.9
```

And using docker-py 0.7.1 and boot2docker v1.4.1.

```
> pip list                                                                                                                                                         backports.ssl-match-hostname (3.4.0.2)
cement (2.4.0)
docker-py (0.7.1)
pip (1.5.6)
puppet-docker (0.1.0)
requests (2.4.3)
setuptools (3.6)
six (1.9.0)
websocket-client (0.23.0)
wsgiref (0.1.2)
```

```
> boot2docker version
Boot2Docker-cli version: v1.4.1
Git commit: 43241cb
```

Note that with the above environment, I can successfully use the official docker CLI.

```
> docker version
Client version: 1.4.1
Client API version: 1.16
Go version (client): go1.3.3
Git commit (client): 5bc2ff8
OS/Arch (client): darwin/amd64
Server version: 1.4.1
Server API version: 1.16
Go version (server): go1.3.3
Git commit (server): 5bc2ff8
```

**Comment by mmerickel** [comment] 2015-01-28 18:52
This is an issue with the homebrew version of Python. I have a custom version of python I compiled myself and everything works fine with it, but the homebrew Python (2.7.9) is broken. I think this is something related to the new openssl 1.0.2 release last week but I haven't tracked down the root issue yet.

**Comment by nmistry** [comment] 2015-02-06 09:12
I can confirm the same issue.   Running the following command seems to be a sufficient workaround, as i already had 1.0.1j_1 installed prior to upgrading to 1.0.2.

```
brew switch openssl 1.0.1j_1
```

**Comment by jiang42** [comment] 2015-02-28 10:20
It seems that requests 2.4.3 can't handle openssl 1.0.2 correctly.

**Comment by kiorky** [comment] 2015-03-02 19:19
on py27, for sni, you need just to install a bunch of other py pkgs: install pyOpenSSL, ndg-httpsclient, pyasn1

**Comment by kiorky** [comment] 2015-03-02 21:36
(to enable python, via monkeypatchs (in requests, that's automatic, the only requirement is that the packages are there) to support server name indication, as it would be on py3.

**Comment by RichardBronosky** [comment] 2015-03-04 00:06
@kiorky care to explain a little more? I have:
    pip install -U pyOpenSSL ndg-httpsclient pyasn1
    Requirement already up-to-date: pyOpenSSL in /usr/local/lib/python2.7/site-packages
    Requirement already up-to-date: ndg-httpsclient in /usr/local/lib/python2.7/site-packages
    Requirement already up-to-date: pyasn1 in /usr/local/lib/python2.7/site-packages
    Requirement already up-to-date: cryptography>=0.2.1 in /usr/local/lib/python2.7/site-packages (from pyOpenSSL)
    Requirement already up-to-date: six>=1.5.2 in /usr/local/lib/python2.7/site-packages (from pyOpenSSL)
    Requirement already up-to-date: cffi>=0.8 in /usr/local/lib/python2.7/site-packages (from cryptography>=0.2.1->pyOpenSSL)
    Requirement already up-to-date: setuptools in /usr/local/lib/python2.7/site-packages (from cryptography>=0.2.1->pyOpenSSL)
    Requirement already up-to-date: enum34 in /Library/Python/2.7/site-packages (from cryptography>=0.2.1->pyOpenSSL)
    Requirement already up-to-date: pycparser in /Library/Python/2.7/site-packages (from cffi>=0.8->cryptography>=0.2.1->pyOpenSSL)

And I get this:
    >>> from docker.client import Client
    >>> from docker.utils import kwargs_from_env
    >>>
    >>> client = Client(**kwargs_from_env())
    >>> print client.version()
    Traceback (most recent call last):
      File "<input>", line 1, in <module>
      File "/usr/local/lib/python2.7/site-packages/docker/client.py", line 905, in version
        return self._result(self._get(self._url("/version")), True)
      File "/usr/local/lib/python2.7/site-packages/docker/client.py", line 82, in _get
        return self.get(url, **self._set_request_timeout(kwargs))
      File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 469, in get
        return self.request('GET', url, **kwargs)
      File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 457, in request
        resp = self.send(prep, **send_kwargs)
      File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 569, in send
        r = adapter.send(request, **kwargs)
      File "/usr/local/lib/python2.7/site-packages/requests/adapters.py", line 362, in send
        timeout=timeout
      File "/usr/local/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 516, in urlopen
        body=body, headers=headers)
      File "/usr/local/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 304, in _make_request
        self._validate_conn(conn)
      File "/usr/local/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 722, in _validate_conn
        conn.connect()
      File "/usr/local/lib/python2.7/site-packages/requests/packages/urllib3/connection.py", line 229, in connect
        ssl_version=resolved_ssl_version)
      File "/usr/local/lib/python2.7/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 249, in ssl_wrap_socket
        ctx = OpenSSL.SSL.Context(_openssl_versions[ssl_version])
    KeyError: 5

**Comment by kiorky** [comment] 2015-03-04 00:32
The traceback you get now is another error.
Maybe trying to access to an old sslv3 only service (see https://github.com/shazow/urllib3/issues/487 ?)

**Comment by steveninmanCubs** [comment] 2015-03-04 22:11
I'm running into this same issue on a newly imaged machine running Python with Beatbox site collection to connect to Salesforce.com
Works fine on all servers except the new one I'm on.  Any other thoughts as these additional components installed via PIP didn't resolve my issue either.

**Comment by shin-** [comment] 2015-03-05 00:29
Hey everyone, did some investigating, can you try setting `TLSConfig.verify` to `True` explicitly and report back if that changed anything?

**Comment by steveninmanCubs** [comment] 2015-03-05 17:29
Shin,
Assuming you are referring to urllib3 libraries within the open ssl python library?  Do you know which call this would need to be set on?  There is no explicit setting for this currently in my installation, so assuming would have to add it to some method call as an additional attribute.

**Comment by shin-** [comment] 2015-03-05 18:05
Sorry, clarifying. Assuming you're using `kwargs_from_env`,

```
kw = kwargs_from_env()
kw['tls'].verify = True
c = docker.Client(**kw)
```

If you're building TLSConfig:
```
tls = docker.utils.TLSConfig(..., verify=True)
```

Thanks!

**Comment by shin-** [comment] 2015-03-05 20:20
Sorry, clarifying. Assuming you're using `kwargs_from_env`,

```python
kw = kwargs_from_env()
kw['tls'].verify = True
c = docker.Client(**kw)
```

If you're building TLSConfig:

```python
tls = docker.utils.TLSConfig(..., verify=True)
c = docker.Client(tls=tls)
```

Thanks!

**Comment by jiang42** [comment] 2015-03-06 08:06
Hi shin,
Set `verify` to `True` explicitly works.

**Comment by steveninmanCubs** [comment] 2015-03-06 14:31
Any clue how to set verify to True within this ssl python method (lowest level of my cert error)?

    def do_handshake(self, block=False):
        """Perform a TLS/SSL handshake."""
        self._check_connected()
        timeout = self.gettimeout()
        try:
            if timeout == 0.0 and block:
                self.settimeout(None)
            self._sslobj.do_handshake()
        finally:
            self.settimeout(timeout)

        if self.context.check_hostname:
            if not self.server_hostname:
                raise ValueError("check_hostname needs server_hostname "
                                 "argument")
            match_hostname(self.getpeercert(), self.server_hostname)

**Comment by steveninmanCubs** [comment] 2015-03-09 21:33
After searching and googling profusely about TLS connections, etc, I noticed this weekend that my cmd.exe window (which I run the PIP commands from) was launching under C:\Windows\System32> and all of my vms were launching within my personal user directory.
So I searched for my roaming cmd.exe and when I opened that, it was to my personal user directory.
After doing an uninstall and install of beatbox using PIP in the new cmd.exe, all of my Salesforce calls via Beatbox work like they used to.
Now I can't fully explain why this is the case, but something tells me that the certs for this admin location are probably mismatched to my personal certificates.  I'm up and running again.

**Comment by shin-** [comment] 2015-03-09 21:38
Thank you for the feedback, seems like we should update the docs to include the `verify=True` option.

**Comment by wardi** [comment] 2015-03-10 15:51
@shin- setting `verify=True` does not work here, but for some reason running from a new virtualenv (built from the system python AFAICT) I don't trigger this problem at all.

**Comment by wardi** [comment] 2015-03-10 16:04
sorry the virtualenv was a red herring, different versions of some dependencies seemed to fix the problem. I'll dig further

**Comment by shin-** [comment] 2015-03-11 00:13
@wardi thanks for the feedback, can you test with current master and updated dependencies? We force a more recent version of requests now, which should help.

**Comment by cancan101** [comment] 2015-03-11 17:39
I installed `docker-py` from master and am I still having this issue.

**Comment by shin-** [comment] 2015-03-11 18:21
@cancan101 Code snippet please, and also details of your environment (OS, docker version, b2d version if applicable)

**Comment by cancan101** [comment] 2015-03-11 18:23
```
client = docker.Client(**kwargs_from_env(assert_hostname=False))
client.version()
```

OS X: Yosemite, Python 2.7.9 (brew)
```
docker version
Client version: 1.5.0
Client API version: 1.17
Go version (client): go1.4.1
Git commit (client): a8a31ef
OS/Arch (client): darwin/amd64
Server version: 1.5.0
Server API version: 1.17
Go version (server): go1.4.1
Git commit (server): a8a31ef
```

**Comment by shin-** [comment] 2015-03-11 18:25
What's the output of `pip freeze | grep requests` ?

**Comment by cancan101** [comment] 2015-03-11 18:27
```
requests==2.5.3
```

**Comment by wardi** [comment] 2015-03-11 18:28
@shin- unfortunately I'm no longer able to reproduce the problem (this was on a colleague's OSX machine) but I couldn't figure out why. It's rather frustrating.

**Comment by shin-** [comment] 2015-03-11 18:32
@cancan101 Can you try to downgrade OpenSSL [as suggested here](https://github.com/docker/docker-py/issues/465#issuecomment-73207729) and see if that helps?

@wardi Alright, thanks for keeping us posted!

**Comment by Julian** [comment] 2015-03-11 18:33
Here's mine:

```
⊙  ~/.local/share/virtualenvs/runner/bin/pypy --version
Python 2.7.8 (10f1b29a2bd21f837090286174a9ca030b8680b2, Feb 05 2015, 17:51:14)
[PyPy 2.5.0 with GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.56)]

⊙  ~/.local/share/virtualenvs/runner/bin/pypy -m pip freeze
backports.ssl-match-hostname==3.4.0.2
betterpath==0.2.2
blessings==1.6
bpython==0.15.dev85
cffi==0.8.6
characteristic==14.3.0
cryptography==0.7.2
curtsies==0.2.3
docker-py==1.0.0
docker-runner==0.1.0.dev0
enum34==1.0.4
greenlet==0.4.5
mock==1.0.1
ndg-httpsclient==0.3.3
pudb==2015.2
pyasn1==0.1.7
Pygments==2.0.2
q==2.5
readline==6.2.4.1
requests==2.4.3
six==1.9.0
toml==0.9.0
Twisted==15.0.0
urwid==1.3.0
vcversioner==2.14.0.0
wcwidth==0.1.4
websocket-client==0.26.0
wheel==0.24.0
zope.interface==4.1.2


```

**Comment by anentropic** [comment] 2015-03-26 17:10
Looks like symptom of same issue here: https://github.com/docker/compose/issues/890

**Comment by RichardBronosky** [comment] 2015-03-26 20:40
pyOpenSSL is causing a lot of problems lately. Similar issue here https://github.com/aws/aws-cli/issues/1240#issuecomment-86213200 and https://github.com/boto/botocore/issues/494

**Comment by dvestal** [comment] 2015-03-31 09:37
@shin- I'm not sure if it's still of any help or not, but since I don't see a response from @cancan101 I wanted to confirm that, in my case, downgrading OpenSSL solves my connection.  I was getting the SSL verification error with an up-to-date homebrew install of python 2.7.9 and openssl 1.0.2a-1.

I uninstalled openssl and python, installed openssl101 from the homebrew/versions tap, changed the dependency in the python.rb formula to be openssl101 instead of openssl.  After building from source everything works fine.

**Comment by zugaldia** [comment] 2015-04-10 15:37
In case it helps, I can also confirm that `brew switch openssl 1.0.1j` solves the issue for me (I was running `1.0.2a-1`).

**Comment by crlane** [comment] 2015-05-15 18:34
@zugaldia 's solution worked for me also.

**Comment by aanand** [comment] 2015-05-28 15:13
I'm also investigating this over on https://github.com/docker/compose/issues/890.

Relevant debug info (would be good to get the same from anyone who either can or can't reproduce):

```
$ python -V
Python 2.7.10
$ python -c 'import ssl; print ssl.OPENSSL_VERSION'
OpenSSL 1.0.2a 19 Mar 2015
```

**Comment by mvd7793** [comment] 2015-05-29 17:27
@aanand I'm having the same problem. Version output:

    ➜  python -V
    Python 2.7.9 
    ➜  python -c 'import ssl; print ssl.OPENSSL_VERSION'
    OpenSSL 1.0.2 22 Jan 2015

**Comment by indygreg** [comment] 2015-06-16 16:27
I was confounded by this issue as well. I spent several hours trying to grok what's going on and I'm convinced there are bugs or limitations in CPython, requests, or urllib3 at play here. I got as far as the C code behind Python's ssl package before I gave up in search of other solutions.

Instead of downgrading OpenSSL versions (that should be a big security red flag), try installing the `requests[security]` or `ndg-httpsclient` package instead. This will pull in `pyasn1`, `pyOpenSSL`, `cryptography` and a bunch of other packages. tl;dr is `ndg-httpsclient` installs an HTTPS client that speaks to pyOpenSSL instead of the built-in ssl package and for whatever reason, doesn't exhibit the issues validating the peer certificate. This solution is working fine for me with Python 2.7.10, openssl 1.0.2c (Homebrew installed), docker-py 0.7.1, and requests[security] 2.7.0 on OS X 10.10.3.

**Comment by aanand** [comment] 2015-06-16 18:00
@indygreg Agreed - using pyOpenSSL seems far preferable, and if you can do that, great.

Unfortunately, using it in Compose is blocking on https://github.com/pyca/cryptography/issues/1524 (we use PyInstaller to package Compose, so any incompatibilities there are a showstopper for us). I've created https://github.com/docker/compose/issues/1530 to keep track of it.

**Comment by stuckeyr** [comment] 2015-06-26 03:25
@indygreg 's workaround was the only solution that worked for me without breaking pip.

**Comment by tdsmith** [comment] 2015-07-17 07:10
Please note that unless you set CPPFLAGS and LDFLAGS carefully when you installed pyOpenSSL's dependency `cryptography`, you are likely to have built pyOpenSSL against OS X's system-installed OpenSSL 0.9.8. You can verify the version of openssl against which `cryptography` is built by running `python -c 'import OpenSSL.SSL as SSL; print SSL.SSLeay_version(SSL.SSLEAY_VERSION)'`.

**Comment by glyph** [comment] 2015-08-01 02:56
I believe the problem here is simply an issue with openssl versions, and the apparent workaround of `ndg-httpsclient` just works if you happen to have built your `cryptography` wheel against the (old) system PyOpenSSL.  You can verify this by looking into your virtualenv like so:

`otool -L $VIRTUAL_ENV/lib/python2.7/site-packages/cryptography/_Cryptography_cffi_* | grep libssl`

If this shows you a `/usr/local/lib/` then you are linked against homebrew; `/usr/lib` and you're linked against the system.

I was able to get Python entirely out of the loop, like so:

```
$ echo | /usr/bin/openssl s_client -verify 9 -cert "${DOCKER_CERT_PATH}/cert.pem" -key "${DOCKER_CERT_PATH}/key.pem" -CAfile "$DOCKER_CERT_PATH/ca.pem" -connect "${DOCKER_HOST#tcp://}" -servername boot2docker 2>&1 | grep Verify
    Verify return code: 0 (ok)
$ echo | /usr/local/bin/openssl s_client -verify 9 -cert "${DOCKER_CERT_PATH}/cert.pem" -key "${DOCKER_CERT_PATH}/key.pem" -CAfile "$DOCKER_CERT_PATH/ca.pem" -connect "${DOCKER_HOST#tcp://}" -servername boot2docker 2>&1 | grep Verify
    Verify return code: 21 (unable to verify the first certificate)
```

Even after years of practice, I still find OpenSSL's error messages completely inscrutable, so this needs more investigation, but it looks like the problem is something broken about how boot2docker is issuing its own certificates.  I *think* the issue might be that the server isn't setting the proper extended key usage for TLS web server authentication, but since the docker command line (and therefore the go TLS implementation) is happy with this certificate, I don't know what's different.

**Comment by glyph** [comment] 2015-08-01 02:59
Thanks very much to @tdsmith for helping me figure this out - the root cause of this issue is almost certainly https://github.com/boot2docker/boot2docker/issues/808

**Comment by glyph** [comment] 2015-08-01 05:14
I tried creating a machine with `docker-machine` rather than `boot2docker` and the certificates generated there seemed to be correct and work with more recent OpenSSL, so that is one possible workaround.

**Comment by posita** [comment] 2015-08-04 16:48
Needs SvenDowideit/generate_cert#10 and boot2docker/boot2docker#808. See https://github.com/docker/compose/issues/890#issuecomment-126854371 et seq. for relevant discussion.

**Comment by posita** [comment] 2015-08-10 03:24
FYI, PR with fix for underlying issue submitted as boot2docker/boot2docker#1029.

**Comment by shin-** [comment] 2015-10-09 00:36
Looks like the referenced PR has been merged on b2d's side. Closing this as a result.

**Closed by shin-** 2015-10-09 00:36 UTC
Labels: documentation, need-info
