### ISSUE TITLE
 timeout when using put_archive method - requests.exceptions.ReadTimeout: UnixHTTPConnectionPool

### ISSUE THREAD

**Issue by gkowalc** [docker/docker-py#3034] opened 2022-08-19 10:37 UTC
I am trying to use container.put_archive method to push tar file (as required by the documentation) file into existing container and I encounter following error: 
`requests.exceptions.ReadTimeout: UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)`

steps to reproduce: 
1) create small .tar file containing few small files 
tar -cvf <my_filename>.tar file1,  file2,  file3`
2) Create and run following python script:

```
 import docker
 import tarfile
 client = docker.from_env()
 container_name = "name_of_the_running_container"
 data = "/Users/<my_username>/<my_filename>.tar"
 file_obj = tarfile.open(data, "r")

 container = client.containers.get(container_name)
 path = "/home/" # target path on container
 container.put_archive(path, file_obj)
```

complete error trace:
```
`Traceback (most recent call last):
  File "/Users/USER/PycharmProjects/pythonProject/task1.py", line 39, in <module>
    for i in client.containers.list():
  File "/Users/USER/PycharmProjects/pythonProject/venv/lib/python3.9/site-packages/docker/models/containers.py", line 961, in list
    containers.append(self.get(r['Id']))
  File "/Users/USER/PycharmProjects/pythonProject/venv/lib/python3.9/site-packages/docker/models/containers.py", line 897, in get
    resp = self.client.api.inspect_container(container_id)
  File "/Users/USER/PycharmProjects/pythonProject/venv/lib/python3.9/site-packages/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/Users/USER/PycharmProjects/pythonProject/venv/lib/python3.9/site-packages/docker/api/container.py", line 772, in inspect_container
    self._get(self._url("/containers/{0}/json", container)), True
  File "/Users/USER/PycharmProjects/pythonProject/venv/lib/python3.9/site-packages/docker/utils/decorators.py", line 46, in inner
    return f(self, *args, **kwargs)
  File "/Users/USER/PycharmProjects/pythonProject/venv/lib/python3.9/site-packages/docker/api/client.py", line 237, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
  File "/Users/USER/PycharmProjects/pythonProject/venv/lib/python3.9/site-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/Users/USER/PycharmProjects/pythonProject/venv/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/USER/PycharmProjects/pythonProject/venv/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/Users/USER/PycharmProjects/pythonProject/venv/lib/python3.9/site-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)`
```

- docker-py version: 5.0.3
- python 3.9 
- OS macOS 11.6.8
- Server: Docker Engine - Community
-  Engine:
-   Version:          20.10.8
-   API version:      1.41 (minimum version 1.12)
Related  problem was reported in the past: https://github.com/docker/docker-py/issues/1808 

Has anyone seen  something similar to my problem? or are you able to reproduce it (which would indicate a bug?

**Comment by milas** [comment] 2022-08-19 18:26
The script you gave (after making a couple changes so it runs) works fine for me:
```python
tar_filename = 'data.tar'
container_id = 'put-archive-test'
dest_path = '/'

import docker
import tarfile
client = docker.from_env()
with open('./docs.tar', 'rb') as f:
    data = f.read()

container = client.containers.get(container_id)
container.put_archive(dest_path, data)
```

I would try increasing the timeout when creating your client, e.g. `client = docker.from_env(timeout=300)`.

Closing as duplicate of #2266.

**Closed by milas** 2022-08-19 18:26 UTC

**Comment by gkowalc** [comment] 2022-08-22 07:53
@milas  Thanks for your reply. 

I don't think my issue is related  #2266 as file size in my case  is really small and shouldn't cause the timeout. 

Anyway your reply verified that problem is limited in its scope to my instance (so not a bug in API). 
I did some extra research and found https://github.com/docker/for-mac/issues/4957 which  includes relevant comment:
https://github.com/docker/for-mac/issues/4957#issuecomment-702282793:
`Does going to "Preferences > General" and unchecking "Use gRPC FUSE for file sharing" fix the issue for you? I was able to get my containers to start after going back to using osxfs.` 
After applying above changing I am not seeing that issue anymore. 

Thanks for looking into it!

**Comment by milas** [comment] 2022-08-23 13:56
Ahh, good find and that's interesting! I'll make note of that and see if I can track down anything.

I know you're on macOS 11.x so it's not an option currently, but when you're able to upgrade to 12.x, I'd recommend giving the experimental VirtioFS accelerated sharing in Docker Desktop an option, it resolves a bunch of edge cases and has better performance!
