### ISSUE TITLE
docker/client.py#_stream_helper can sometimes be given multiline input

### ISSUE THREAD

**Issue by dgjnpr** [docker/docker-py#1134] opened 2016-07-19 14:01 UTC
There appears to be some kind of intermittent race condition that results in _stream_helper() reading a multiline string. This causes the json parser to stacktrace. Here is an example. I've modified _stream_helper() to print debug messages at the start and end of data chunks it receives:

```
Traceback (most recent call last):
  File "/Users/dgethings/.ansible/tmp/ansible-tmp-1468925027.86-15206280689556/debug_dir/ansible_module_docker_image.py", line 532, in <module>
    main()
  File "/Users/dgethings/.ansible/tmp/ansible-tmp-1468925027.86-15206280689556/debug_dir/ansible_module_docker_image.py", line 524, in main
    ImageManager(client, results)
  File "/Users/dgethings/.ansible/tmp/ansible-tmp-1468925027.86-15206280689556/debug_dir/ansible_module_docker_image.py", line 244, in __init__
    self.present()
  File "/Users/dgethings/.ansible/tmp/ansible-tmp-1468925027.86-15206280689556/debug_dir/ansible_module_docker_image.py", line 273, in present
    self.results['image'] = self.build_image()
  File "/Users/dgethings/.ansible/tmp/ansible-tmp-1468925027.86-15206280689556/debug_dir/ansible_module_docker_image.py", line 458, in build_image
    for line in self.client.build(**params):
  File "/Library/Python/2.7/site-packages/docker/client.py", line 234, in _stream_helper
    data = json.loads(data)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 369, in decode
    raise ValueError(errmsg("Extra data", s, end, len(s)))
ValueError: Extra data: line 2 column 1 - line 4 column 1 (char 63 - 224)
debug: {"stream":"Step 1 : FROM jenkins:2.7.1-alpine\n"}
 :end
debug: {"status":"Pulling from library/jenkins","id":"2.7.1-alpine"}
{"status":"Digest: sha256:031c2be684f7aa8b50684ca9b0517e6b3d3f86912e879b77cfe5ef002581980d"}
{"status":"Status: Image is up to date for jenkins:2.7.1-alpine"}
 :end
```
Notice the last lines of output. In this instance the variable ```data``` contains 3 lines. This causes ```json.loads(data)``` to stacktrace. Unfortunately my Python is not good enough to work out the best way to resolve this problem. But I would be prepared to pair with someone.

Here's the version info:
```
$ pip freeze | grep docker-py && python --version && docker version
docker-py==1.8.1
Python 2.7.10
Client:
 Version:      1.12.0-rc4
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   e4a0dbc
 Built:        Wed Jul 13 03:28:51 2016
 OS/Arch:      darwin/amd64
 Experimental: true

Server:
 Version:      1.12.0-rc4
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   e4a0dbc
 Built:        Wed Jul 13 03:28:51 2016
 OS/Arch:      linux/amd64
 Experimental: true
```

**Comment by himslm01** [comment] 2016-07-23 13:51
I found this issue and worked around it in my code - then I searched github and found this issue.
I do this in my code, as a work around. I don't know how brittle it is, but it's working for now.

```
from docker import Client
import json

cli = Client(base_url='unix://var/run/docker.sock')
generator = cli.build(..., stream=True, decode=False, ...)
for block in generator:
#    print 'block::' + block
    for line in block.splitlines():
#        print 'line::' + line
        try:
            data = json.loads(line)
            ...
```

**Comment by shin-** [comment] 2016-07-25 18:31
I believe this is a duplicate of #1059 . Please refer to that issue for progress and resolution.

**Closed by shin-** 2016-07-25 18:31 UTC
