### ISSUE TITLE
How can I run the next command which is on the basis of the previous command

### ISSUE THREAD

**Issue by NeverWait** [docker/docker-py#2269] opened 2019-03-07 15:09 UTC
such as I only have a  redis docker and I have set the key is 'hi' and the value is 'ha', I write this command
`# -*- coding: utf-8 -*-

import docker

client = docker.from_env()
dockerList = client.containers.list()[0] 
res = dockerList.exec_run("redis-cli")
resCode, resMsg  = res[0], res[1]
if 0 == resCode:
    print(dockerList.exec_run("get hi"))`

It printed ' \\"get\\": executable file not found in $PATH": unknown\r\n ', the second command should have been on the basis of the previous command. In fact I have the third and the forth command are on the basis of the previous command, can I reach my goals using docker-py? Thanks lot.

**Comment by ijc** [comment] 2019-03-07 16:34
I'm afraid your reproduction steps are not complete enough to be able to help (you haven't said how your redis was deployed, not which version nor how it is setup).

I do know that there is no `get` command in the `redis:latest` container I just pushed.

Your example `dockerList.exec_run("get hi"))` is trying to run `get` as a new command inside the container. You need to pass `socket=True` to your first `exec_run` and then interact with the resulting socket option in order to interact with the `redis-cli`.

I hope that is enough to get you going. I'm going to close this issue, since this is not really a support forum. Please consult the docs (https://docker-py.readthedocs.io/en/stable/) carefully.

**Closed by ijc** 2019-03-07 16:34 UTC
