### ISSUE TITLE
SSL: CERTIFICATE_VERIFY_FAILED error with docker-py and with pycurl, all fine.

### ISSUE THREAD

**Issue by jiang42** [docker/docker-py#510] opened 2015-02-28 05:36 UTC
Hi, I follow the instruction in https://docs.docker.com/articles/https/ to provide my docker daemon ability to communicate with outside world. However, I can't connect my docker daemon with docker-py. And with pycurl, all fine.

Client:
System: Mac OS X 10.9.5
Python version: 3.4.2
pycurl version: PycURL/7.19.5.1 libcurl/7.41.0 OpenSSL/1.0.2 zlib/1.2.8 libidn/1.29
docker-py version: 1.0.0

Server:
System: Ubuntu 14.04
docker: 1.5.0

code with pycurl:
```python
import pycurl
c = pycurl.Curl()
c.setopt(pycurl.URL, 'https://Aries:2376/v1.17/images/json')
c.setopt(pycurl.SSLCERTTYPE, 'PEM')
c.setopt(pycurl.SSLKEYTYPE, 'PEM')
c.setopt(pycurl.CAINFO, '/path/to/docker/ca.pem')
c.setopt(pycurl.SSLCERT, '/path/to/docker/cert.pem')
c.setopt(pycurl.SSLKEY, '/path/to/docker/key.pem')

import io
buffer = io.BytesIO()
c.setopt(pycurl.WRITEDATA, buffer)

c.perform()
c.close()
```

code with docker-py:
```python
import docker

tls_config = docker.tls.TLSConfig(
    client_cert=('/path/to/docker/cert.pem', '/path/to/docker/key.pem'),
    ca_cert='/path/to/docker/ca.pem'
    )
client = docker.Client(base_url='https://Aries:2376', tls=tls_config)
client.images()
```
error message:
```python
---------------------------------------------------------------------------
SSLError                                  Traceback (most recent call last)
<ipython-input-4-8e1547ab2e5e> in <module>()
----> 1 client.images()

/Users/jiang/virtualenv/Libra-3.4/lib/python3.4/site-packages/docker/client.py in images(self, name, quiet, all, viz, filters)
    532         if filters:
    533             params['filters'] = utils.convert_filters(filters)
--> 534         res = self._result(self._get(self._url("/images/json"), params=params),
    535                            True)
    536         if quiet:

/Users/jiang/virtualenv/Libra-3.4/lib/python3.4/site-packages/docker/client.py in _get(self, url, **kwargs)
     80 
     81     def _get(self, url, **kwargs):
---> 82         return self.get(url, **self._set_request_timeout(kwargs))
     83 
     84     def _delete(self, url, **kwargs):

/Users/jiang/virtualenv/Libra-3.4/lib/python3.4/site-packages/requests/sessions.py in get(self, url, **kwargs)
    467 
    468         kwargs.setdefault('allow_redirects', True)
--> 469         return self.request('GET', url, **kwargs)
    470 
    471     def options(self, url, **kwargs):

/Users/jiang/virtualenv/Libra-3.4/lib/python3.4/site-packages/requests/sessions.py in request(self, method, url, params, data, headers, cookies, files, auth, timeout, allow_redirects, proxies, hooks, stream, verify, cert, json)
    455         }
    456         send_kwargs.update(settings)
--> 457         resp = self.send(prep, **send_kwargs)
    458 
    459         return resp

/Users/jiang/virtualenv/Libra-3.4/lib/python3.4/site-packages/requests/sessions.py in send(self, request, **kwargs)
    567 
    568         # Send the request
--> 569         r = adapter.send(request, **kwargs)
    570 
    571         # Total elapsed time of the request (approximately)

/Users/jiang/virtualenv/Libra-3.4/lib/python3.4/site-packages/requests/adapters.py in send(self, request, stream, timeout, verify, cert, proxies)
    418         except (_SSLError, _HTTPError) as e:
    419             if isinstance(e, _SSLError):
--> 420                 raise SSLError(e, request=request)
    421             elif isinstance(e, ReadTimeoutError):
    422                 raise ReadTimeout(e, request=request)

SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)
```

**Comment by shin-** [comment] 2015-03-02 18:57
Duplicate of #465

**Closed by shin-** 2015-03-02 18:57 UTC

**Comment by abhishekkarigar** [comment] 2019-04-27 19:43
use 
client = docker.client.APIClient(base_url="")
