### ISSUE TITLE
AttributeError: 'module' object has no attribute 'connection'

### ISSUE THREAD

**Issue by dkhabarov** [docker/docker-py#1179] opened 2016-09-01 09:23 UTC
```
# pip freeze | grep docker-py && python --version && docker version
docker-py==1.9.0
Python 2.7.6
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:22:43 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:22:43 2016
 OS/Arch:      linux/amd64
```
Os: Ubuntu 14.4.4.

```
In [1]: import docker
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-1-3ac1c348f58a> in <module>()
----> 1 import docker

/usr/local/lib/python2.7/dist-packages/docker/__init__.py in <module>()
     18 __title__ = 'docker-py'
     19 
---> 20 from .client import Client, AutoVersionClient, from_env # flake8: noqa

/usr/local/lib/python2.7/dist-packages/docker/client.py in <module>()
     22 
     23 
---> 24 from . import api
     25 from . import constants
     26 from . import errors

/usr/local/lib/python2.7/dist-packages/docker/api/__init__.py in <module>()
      1 # flake8: noqa
----> 2 from .build import BuildApiMixin
      3 from .container import ContainerApiMixin
      4 from .daemon import DaemonApiMixin
      5 from .exec_api import ExecApiMixin

/usr/local/lib/python2.7/dist-packages/docker/api/build.py in <module>()
      7 from .. import errors
      8 from .. import auth
----> 9 from .. import utils
     10 
     11 

/usr/local/lib/python2.7/dist-packages/docker/utils/__init__.py in <module>()
----> 1 from .utils import (
      2     compare_version, convert_port_bindings, convert_volume_binds,
      3     mkbuildcontext, tar, exclude_paths, parse_repository_tag, parse_host,
      4     kwargs_from_env, convert_filters, datetime_to_timestamp, create_host_config,
      5     create_container_config, parse_bytes, ping_registry, parse_env_file,

/usr/local/lib/python2.7/dist-packages/docker/utils/utils.py in <module>()
     31 from .. import constants
     32 from .. import errors
---> 33 from .. import tls
     34 from .types import Ulimit, LogConfig
     35 

/usr/local/lib/python2.7/dist-packages/docker/tls.py in <module>()
      3 
      4 from . import errors
----> 5 from .ssladapter import ssladapter
      6 
      7 

/usr/local/lib/python2.7/dist-packages/docker/ssladapter/__init__.py in <module>()
----> 1 from .ssladapter import SSLAdapter # flake8: noqa

/usr/local/lib/python2.7/dist-packages/docker/ssladapter/ssladapter.py in <module>()
     20 if sys.version_info[0] < 3 or sys.version_info[1] < 5:
     21     from backports.ssl_match_hostname import match_hostname
---> 22     urllib3.connection.match_hostname = match_hostname
     23 
     24 

AttributeError: 'module' object has no attribute 'connection'
```

**Comment by shin-** [comment] 2016-09-01 19:16
Hi, I believe this is a duplicate of #1054 . Please refer to that other issue for an explanation of the bug and possible workarounds.

**Closed** 2016-09-01 19:16 UTC
Labels: duplicate
