### ISSUE TITLE
dummy information using logs API

### ISSUE THREAD

**Issue by linlinlinlin** [docker/docker-py#579] opened 2015-04-30 04:01 UTC
#### Using docker logs command

     ken@ubuntu ~/ $ curl "http://127.0.0.1:2376/v1.18/containers/c8f53651e1bf/logs?stdout=1"
     root@c8f53651e1bf:/# exit

#### Using docker-py API

    In [4]: c.logs('c8f53651e1bf')
    Out[4]: '@c8f53651e1bf: /\x07root@c8f53651e1bf:/# exit\n'

Issue:
The output of *@ c8f53651e1bf:* in the beginning was incorrect.

**Comment by shin-** [comment] 2015-05-07 17:55
Thank you for the report! Reproduction steps would be extremely helpful if possible (i.e. which image did you use, what parameters did you use in the create / start methods, etc.)

**Comment by linlinlinlin** [comment] 2015-05-07 23:19
Image: `ubuntu:latest`
Create container command:  `docker run -it ubuntu bash `

**Comment by garthy** [comment] 2015-06-11 14:31
This is because logs doesn't return the byte headers so the value gets truncated by header bytes.

Run `docker run -t -i ubuntu  /bin/bash -c 'echo "Hello this is a bug"'`

The stdout is `docker logs <containerid>`
`Hello this is a bug`

Then run the code 

    import sys
    import docker
    container = sys.argv[1]
    klint = docker.Client(base_url='unix://var/run/docker.sock')
    print "LOGS:",
    print klint.logs(container,stdout=True, stderr=True, stream=False, timestamps=False)

This prints 

    LOGS: is is a bug


This is with the following on Linux Mint

    $ docker version
    Client version: 1.6.2
    Client API version: 1.18
    Go version (client): go1.4.2
    Git commit (client): 7c8fca2
    OS/Arch (client): linux/amd64
    Server version: 1.6.2
    Server API version: 1.18
    Go version (server): go1.4.2
    Git commit (server): 7c8fca2
    OS/Arch (server): linux/amd64

**Comment by garthy** [comment] 2015-06-11 15:16
OK this only seems to be the case when I create a container with

stdin_open (bool): Keep STDIN open even if not attached
tty (bool): Allocate a pseudo-TTY

If these are not set then the header bytes exist as part of the stream

**Comment by garthy** [comment] 2015-06-11 15:18
from the Docker API docs..

Stream details:

When using the TTY setting is enabled in POST /containers/create, the stream is the raw data from the process PTY and client's stdin. When the TTY is disabled, then the stream is multiplexed to separate stdout and stderr.

**Comment by aanand** [comment] 2015-07-03 09:30
Is this the same issue as #630?

**Comment by garthy** [comment] 2015-07-03 13:32
Yes.

**Comment by shin-** [comment] 2015-07-08 20:32
Closing via #669

**Closed by shin-** 2015-07-08 20:32 UTC
Labels: bug
