### ISSUE TITLE
conflicting documentation for images api

### ISSUE THREAD

**Issue by jamesongithub** [docker/docker-py#1470] opened 2017-02-20 19:18 UTC
https://docker-py.readthedocs.io/en/stable/images.html#docker.models.images.ImageCollection.build seem to indicate it returns an image object

the parameters like `stream` and `decode` don't seem to jive with this

**Comment by shin-** [comment] 2017-02-21 19:57
I believe this is a duplicate of #1400

**Comment by shin-** [comment] 2017-02-21 19:57
Will be fixed by #1420

**Closed by shin-** 2017-02-21 19:57 UTC
Labels: group/documentation, status/duplicate
