### ISSUE TITLE
Bad Request ("starting container with non-empty request body was deprecated since API v1.22 and removed in v1.24")

### ISSUE THREAD

**Issue by valentinedwv** [docker/docker-py#3162] opened 2023-07-21 21:55 UTC
https://github.com/docker/docker-py/blob/84414e343e526cf93f285284dd2c2c40f703e4a9/docker/api/container.py#L1126C27-L1126C27

Can this be changed to:
self._post(url, data={})

**Comment by naufalafif** [comment] 2023-07-22 01:37
can you give more details why you want to change it ? 

starting container required no data except the container ID as path params, so no request body in the process. 
you can refer to docker API https://docs.docker.com/engine/api/v1.43/#tag/Container/operation/ContainerStart

**Comment by valentinedwv** [comment] 2023-07-22 02:04
If I send an empty body, I get that error.
At least let us pass an data

**Comment by naufalafif** [comment] 2023-07-22 02:36
I see. I have tried it & seems to work well without any issues.

Can you try code below & share the logs/output. It should print `Hello, Docker!`
```python
import docker

# Create a Docker client
client = docker.from_env()

# Create a container
container = client.containers.create(
    image='ubuntu:latest',
    command='echo "Hello, Docker!"',
    detach=True
)

# Start the container
container.start()

# Wait for the container to finish running
container.wait()

# Get the container logs
logs = container.logs().decode('utf-8')
print(logs)

# Remove the container
container.remove()
```

**Comment by valentinedwv** [comment] 2023-07-22 17:32
Humm. yes, ran straight on host and got:
`Hello, Docker!`

So, this is an issue with how Portainer is proxying the docker API...
Exactly what I am doing is trying to use the Portainer docker endpoint in a dagster 'op' to run a container.

For some reason it's triggering[ this issue](https://github.com/docker/docker-ce/blob/44a430f4c43e61c95d4e9e9fd6a0573fa113a119/components/engine/api/server/router/container/container_routes.go#L171)

Filed an issue with [portainer](https://github.com/portainer/portainer/issues/9239)

but it would be nice to have a body passed through. Otherwise we are directly calling the api via requests. It works.

Thanks for your time. Looks like its some golang library issue.

**Comment by naufalafif** [comment] 2023-08-02 03:14
Hi @valentinedwv , glad to know u have found the root cause.
i think you can close this issue

**Closed** 2023-08-02 14:10 UTC
