### ISSUE TITLE
"'SocketIO' object has no attribute 'raw'" exception when running Docker Compose attached

### ISSUE THREAD

**Issue by tomelliff** [docker/docker-py#1800] opened 2017-11-08 11:42 UTC
We have a CI pipeline running that executes some blackbox integration tests via Docker-Compose (to setup all the required services). Since this morning these tests have been failing with the following stack trace as Docker-Compose runs the task that executes the tests:
```
Creating dd07eb4697ed0ce2ddea5e4ce97b4175299c8dee_meshing_service_1 ... 
Creating dd07eb4697ed0ce2ddea5e4ce97b4175299c8dee_s3_1 ... 
Creating dd07eb4697ed0ce2ddea5e4ce97b4175299c8dee_meshing_service_1
Creating dd07eb4697ed0ce2ddea5e4ce97b4175299c8dee_s3_1

ERROR: for dd07eb4697ed0ce2ddea5e4ce97b4175299c8dee_meshing_service_1  'SocketIO' object has no attribute 'raw'

ERROR: for dd07eb4697ed0ce2ddea5e4ce97b4175299c8dee_s3_1  'SocketIO' object has no attribute 'raw'

ERROR: for meshing_service  'SocketIO' object has no attribute 'raw'

ERROR: for s3  'SocketIO' object has no attribute 'raw'
Traceback (most recent call last):
  File "/usr/bin/docker-compose", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python3.6/site-packages/compose/cli/main.py", line 68, in main
    command()
  File "/usr/lib/python3.6/site-packages/compose/cli/main.py", line 121, in perform_command
    handler(command, command_options)
  File "/usr/lib/python3.6/site-packages/compose/cli/main.py", line 768, in run
    run_one_off_container(container_options, self.project, service, options)
  File "/usr/lib/python3.6/site-packages/compose/cli/main.py", line 1170, in run_one_off_container
    rescale=False
  File "/usr/lib/python3.6/site-packages/compose/project.py", line 455, in up
    get_deps,
  File "/usr/lib/python3.6/site-packages/compose/parallel.py", line 70, in parallel_execute
    raise error_to_reraise
  File "/usr/lib/python3.6/site-packages/compose/parallel.py", line 168, in producer
    result = func(obj)
  File "/usr/lib/python3.6/site-packages/compose/project.py", line 441, in do
    start=start
  File "/usr/lib/python3.6/site-packages/compose/service.py", line 471, in execute_convergence_plan
    scale, detached, start
  File "/usr/lib/python3.6/site-packages/compose/service.py", line 396, in _execute_convergence_create
    "Creating",
  File "/usr/lib/python3.6/site-packages/compose/parallel.py", line 70, in parallel_execute
    raise error_to_reraise
  File "/usr/lib/python3.6/site-packages/compose/parallel.py", line 168, in producer
    result = func(obj)
  File "/usr/lib/python3.6/site-packages/compose/service.py", line 394, in <lambda>
    lambda n: create_and_start(self, n),
  File "/usr/lib/python3.6/site-packages/compose/service.py", line 387, in create_and_start
    container.attach_log_stream()
  File "/usr/lib/python3.6/site-packages/compose/container.py", line 177, in attach_log_stream
    self.log_stream = self.attach(stdout=True, stderr=True, stream=True)
  File "/usr/lib/python3.6/site-packages/compose/container.py", line 254, in attach
    return self.client.attach(self.id, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/docker/api/container.py", line 56, in attach
    response, stream, self._check_is_tty(container)
  File "/usr/lib/python3.6/site-packages/docker/api/client.py", line 368, in _read_from_socket
    socket = self._get_raw_response_socket(response)
  File "/usr/lib/python3.6/site-packages/docker/api/client.py", line 276, in _get_raw_response_socket
    sock = response.raw._fp.fp.raw
AttributeError: 'SocketIO' object has no attribute 'raw'
```
Oddly I can't seem to get this to fail completely locally with the latest Docker-Compose and Docker:
```
$ pip freeze | grep docker
docker==2.6.0
docker-compose==1.17.0
docker-pycreds==0.2.1
dockerpty==0.4.1
```
but it does fail when I run the tests locally in our CI container (built from the official Docker image) when bind mounting the docker socket into the container. The only things that stand out there for me is that it's running Alpine and Python 3.6 compared to my local Ubuntu 16.04 and Python 2.7.

I've also noticed that running Docker-Compose detached doesn't cause the issue but I'm not yet sure why that's the case. All I know is that the `docker` Python package was bumped in between things working and now them failing so I guess a regression has sneaked in somewhere.

**Comment by lelit** [comment] 2017-11-08 12:04
I hit this too, in a similar scenario, except that the CI pipeline runs on top of Python 3.6 _normal_ image, not Alpine.

**Comment by shin-** [comment] 2017-11-08 20:07
Duplicate of #1799, but I'll take the extra info into account, thanks!

**Closed by shin-** 2017-11-08 20:07 UTC
