### ISSUE TITLE
remove_container raise cannot concatenate 'str' and 'NoneType' objects (HTTP 500)

### ISSUE THREAD

**Issue by Fangfenghua** [docker/docker-py#545] opened 2015-04-13 09:06 UTC
if call remove_container with container={} will got error:
 cannot concatenate 'str' and 'NoneType' objects (HTTP 500)
should we check the container is None?

**Comment by TomasTomecek** [comment] 2015-04-13 11:32
If you check the code, none of the methods check `image` nor `container`. To me, it would make sense to add such checks. At least for `None`, as you pointed out.

**Comment by shin-** [comment] 2015-04-22 21:03
Thank you for the report! Closing as a duplicate of #517

**Closed by shin-** 2015-04-22 21:03 UTC
Labels: enhancement
