### ISSUE TITLE
expand_registry_url doesn't use authentication

### ISSUE THREAD

**Issue by newhook** [docker/docker-py#650] opened 2015-06-24 18:52 UTC
The function does:

 if utils.ping_registry('https://' + hostname):
        return 'https://' + hostname

However, this ping doesn't use the auth information meaning that it will fail if the registry requires an authenticated user.

**Comment by shin-** [comment] 2015-06-24 18:55
Duplicate of #617 !

**Comment by newhook** [comment] 2015-06-24 18:55
Thanks!

**Closed by shin-** 2015-06-24 18:55 UTC
