### ISSUE TITLE
Revert use of environment markers in extras_require

### ISSUE THREAD

**Issue by andornaut** [docker/docker-py#1019] opened 2016-04-01 20:51 UTC
The use of an "environment marker" in the ``extras_require`` dict in #1018 is not compatible with earlier versions of Python 2:
```
python --version
pushd $(mktemp -d) >/dev/null
git clone -q https://github.com/docker/docker-py.git
virtualenv -q pip
virtualenv -q setuptools

source setuptools/bin/activate
pushd ./docker-py >/dev/null
python setup.py install >/dev/null
popd >/dev/null
pip freeze|grep ipaddress

source pip/bin/activate
pip install -qU pip
pushd ./docker-py  >/dev/null
pip install -q .
popd >/dev/null
pip freeze|grep ipaddress
popd >/dev/null
```

Output on Python 2.7.10
```
Python 2.7.10
py2-ipaddress==3.4.1
py2-ipaddress==3.4.1
```

Output on Python 2.7.3
```
Python 2.7.3
error in docker-py setup command: Invalid environment marker: python_version < "3"
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-XrHLjZ-build/
```

**Comment by shin-** [comment] 2016-04-01 22:10
Can this be fixed by updating your `setuptools` package? I just tested it with Python 2.7.7 and simply doing `pip install -U setuptools` seems to solve the problem.

**Comment by andornaut** [comment] 2016-04-04 12:57
> Can this be fixed by updating your setuptools package?

Yep, however, it'd be nice if docker-py continued to work with older versions of setuptools.

**Comment by jneureuther** [comment] 2016-05-18 22:36
This should be fixed asap since it breaks travis-ci builds: https://travis-ci.org/jneureuther/dockgraph/jobs/131267651#L287

**Comment by shin-** [comment] 2016-05-18 22:45
There is no "fix" planned - this is not a bug. Please update your version of `setuptools` to support the environment marker syntax.

**Comment by jneureuther** [comment] 2016-05-18 22:47
Thank you for clarifying this. Then i would suggest to close this issue?

**Closed** 2016-05-18 22:49 UTC
Labels: wontfix
