### ISSUE TITLE
Client pull() doesn't throw error properly

### ISSUE THREAD

**Issue by jamespharaoh** [docker/docker-py#467] opened 2015-01-29 16:50 UTC
If I understand it correctly, the API is supposed to throw an error if the API call does not complete properly.

When there is an error I get a string which has json in it, and can see the error in there, but no exception is thrown.

Here's some illustrative code:

```
result = self.client.pull(image, tag=tag)
print ("%s" % result)
print ("%s" % type(result))
```

And here's what we get from it:

```
{"errorDetail":{"message":"HTTP code: 403"},"error":"HTTP code: 403"}
<type 'unicode'>
```

I have tried to fix this myself but can't work it out. If someone can give me some hints I'll have another go.

I am still trying to work out why the auth is failing, which I think is another issue, since this works fine from the command line...

**Comment by gtaylor** [comment] 2015-02-05 05:23
Not entirely your particular set of symptoms, but I was playing around with pull() on my own and noticed that passing in an invalid image/tag results in something like this:

```
Status Code: 200

{"status":"Pulling repository blartyblartyblarty"}
{"errorDetail":{"message":"Error: image library/blartyblartyblarty: not found"},"error":"Error: image library/blartyblartyblarty: not found"}
```

A look at the [Docker API docs](http://docs.docker.com/reference/api/docker_remote_api_v1.15/#create-an-image) showed that sure enough, only 200 or 500 are listed as probable response codes. On the docker-py side, [raise_for_status()](https://github.com/docker/docker-py/blob/master/docker/client.py#L96) is being called correctly, but the Docker API is sending a 200 (meaning no exception is raised).

It might be worth checking and seeing if you are actually getting an HTTP 200 instead of a 403, even though the body is saying 403. I may be way off on this, but figured I'd share a somewhat related experience.

**Comment by jamespharaoh** [comment] 2015-02-05 06:45
Ok well I found and fixed the #468 which was the cause of the error for me, so this doesn't affect me. From what you say, this would be a problem with docker really, correct? They should be returning an appropriate error code in the case of faliure...

**Comment by gtaylor** [comment] 2015-02-05 06:52
I'm not too in touch with how the Docker API was designed, so I'm not sure if these 200's with error messages were intentionally done this way for a reason. From my uninformed third party perspective, I'd definitely expect a 400 when attempting to build an invalid image (as per the previously shown example).

Whether this means filing an upstream bug in docker itself (seems like someone would have complained about this by now), or figuring out how to handle it in docker-py, I have no idea.

Hopefully my outlined case is just another relevant data point :)

**Comment by jamespharaoh** [comment] 2015-02-05 20:55
ok this is already reported in docker, but with no activity:
https://github.com/docker/docker/issues/8844

**Comment by gtaylor** [comment] 2015-02-05 20:58
Subscribed! At least it's been reported before. I would have figured there'd be more than a few people asking about this.

**Comment by shin-** [comment] 2015-02-06 22:36
Well, the issue here I think is that we have started streaming the pull logs (i.e. started writing the HTTP response body) which means we can't modify the HTTP status code. SInce no error was found at the moment the request is processed, the status code is 200.

An error during the pull is then simply reported in the logs themselves and since we have a very hands off approach to the data that comes out of there, docker-py doesn't transform it into an exception. The tradeoff is speed of execution (no JSON parsing / extra processing) VS convenience (Having an exception raised when an error occurs in the pull/push/build logs).

For this specifically:
```json
{"errorDetail":{"message":"HTTP code: 403"},"error":"HTTP code: 403"}
```

It seems this was raised by either the registry or the DockerHub. The context should give you more information regarding which step failed. If you're working with a private registry, note that 0.7.2 fixed an auth bug with those, so this could be related.

**Comment by shin-** [comment] 2016-12-13 01:01
I believe this has now been fixed in the engine.

**Closed by shin-** 2016-12-13 01:01 UTC
Labels: tools-project
