### ISSUE TITLE
Exit code of the command executed through execute API is not available

### ISSUE THREAD

**Issue by utyagi24** [docker/docker-py#550] opened 2015-04-22 17:12 UTC
Docker version 1.5.0, build a8a31ef
docker-py 1.1.0

I am trying something like following - 
c.execute(container_id, cmd='some command', detach=False, stdout=True, stderr=True, stream=False, tty=False)
logging.info('Exec output- '+ str(output))

The command executes and I am able to log the command output too, but there seems to be no way to determine the exit code of the command. The equivalent Docker CLI however does provide the correct exit code - 

$ docker exec 0ba0e77d5c38 ls xxx
ls: cannot access xxx: No such file or directory
$ echo $?
2

$ docker exec 0ba0e77d5c38 ls
bin
...
$ echo $?
0

**Comment by shin-** [comment] 2015-04-22 17:52
Closing as duplicate of #444

**Closed by shin-** 2015-04-22 17:52 UTC
