### ISSUE TITLE
service list fail if empty

### ISSUE THREAD

**Issue by kiddo3** [docker/docker-py#1970] opened 2018-03-20 11:41 UTC
Calling the client with some filters, if no services matches a exception is thrown:
client.services.list(filters=filters)

  File "************docker/docker/dockercli.py", line 13, in listServices
    services = self.client.services.list(filters=filters)
  File "*********/lib/python3.5/site-packages/docker/models/services.py", line 259, in list
    for s in self.client.api.services(**kwargs)
TypeError: 'NoneType' object is not iterable

**Comment by ChrsMark** [comment] 2018-06-01 12:08
Cannot reproduce:
- Docker version 1.13.1

```
>>> import docker
>>> cli = docker.from_env()
>>> cli.services.list(filters={'name': 'redis'})
[<Service: ksfy1yhgko>]
>>> cli.services.list(filters={'name': 'redis1'})
[]
>>> docker.version
'3.4.0-dev'
```

**Comment by ijc** [comment] 2019-04-05 15:23
Closing since the previous comment indicates this isn't reproducible. If you are still having this issue please provide repro steps.

**Closed by ijc** 2019-04-05 15:23 UTC
Labels: kind/bug
