### ISSUE TITLE
Support encrypted (password-protected) SSH key files

### ISSUE THREAD

**Issue by MonkeeMan1** [docker/docker-py#3061] opened 2022-10-28 22:40 UTC
I'm currently trying to use the dockerpy sdk to connect to my remote ubuntu server so i can manage my docker containers via python.

I am getting a few issues when attempting to do this.

```python
docker.APIClient(base_url="ssh://user@ip")
```
When doing the following I am getting the error: 

```
paramiko.ssh_exception.PasswordRequiredException: private key file is encrypted
```
I can resolve this issue by adding the kwarg: `use_ssh_client`, but then i am forced to input a password, which limits the potential for automation.
```python
docker.APIClient(base_url="ssh://user:@ip", use_ssh_client=True)
```
When using the above code, I have also tried to enter my ssh key password into the base_url such as:
```
docker.APIClient(base_url="ssh://user:pass@ip", use_ssh_client=True)
```
However, this then greets me with the following error:
```
docker.errors.DockerException: Invalid bind address format: ssh://root:pass@ip
```
I have run out of ideas and am confused as to how I am supposed to get around this?

Many thanks in advance...

**Comment by milas** [comment] 2022-11-01 16:57
Currently, there's no support for programmatically passing a password for encrypted SSH key files - added the "feature request" label here.

Here's the relevant code that sets up the SSH connection via Paramiko for reference: https://github.com/docker/docker-py/blob/bc0a5fbacd7617fd338d121adca61600fc70d221/docker/transport/sshconn.py#L189-L218

**Comment by milas** [comment] 2022-11-01 16:57
Actually closing this as a duplicate of #2416.

**Closed by milas** 2022-11-01 16:57 UTC
Labels: kind/feature-request
