### ISSUE TITLE
TypeError: 'exceptions.ValueError' object is not callable, when using client.service.create()

### ISSUE THREAD

**Issue by mbovo** [docker/docker-py#1827] opened 2017-12-01 09:13 UTC
Call to client.service.create() fails without understandable error with the following trace:
```
e = HTTPError(u'500 Server Error: Internal Server Error for url: http+docker://localunixsocket/v1.32/services/create',)

    def create_api_error_from_http_exception(e):
        """
        Create a suitable APIError from requests.exceptions.HTTPError.
        """
        response = e.response
        try:
            explanation = response.json()['message']
        except ValueError:
            explanation = response.content.strip()
        cls = APIError
        if response.status_code == 404:
            if explanation and ('No such image' in str(explanation) or
                                'not found: does not exist or no pull access'
                                in str(explanation) or
                                'repository does not exist' in str(explanation)):
                cls = ImageNotFound
            else:
                cls = NotFound
>       raise cls(e, response=response, explanation=explanation)
E       TypeError: 'exceptions.ValueError' object is not callable
```

Notes:
client object has been created using version="1.32" but same result with version='auto' or without version

Info:
```
docker==2.6.1
docker-pycreds==0.2.1
Python 2.7.13
Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:40:09 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:45:38 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

**Comment by mbovo** [comment] 2017-12-11 15:01
Maybe with a clearer title and text the issue won't be ignored for 10 days....

**Comment by shin-** [comment] 2017-12-14 01:19
Thanks for the report! Does the patch at #1828 help at all?

**Comment by shin-** [comment] 2017-12-14 01:29
Also, what version of `requests` are you using? Does the error change if you install a different version of `requests`?

**Comment by mbovo** [comment] 2017-12-14 14:22
Hi @shin-  thanks for your reply, `requests` version is `2.18.4`. I've tried also with 2.18.0 and 2.17.0 but the error still persists.
At the time I'm testing fix #1828 with no changes:
```
venv/lib/python2.7/site-packages/docker/models/services.py:177: in create
    service_id = self.client.api.create_service(**create_kwargs)
venv/lib/python2.7/site-packages/docker/utils/decorators.py:34: in wrapper
    return f(self, *args, **kwargs)
venv/lib/python2.7/site-packages/docker/api/service.py:134: in create_service
    self._post_json(url, data=data, headers=headers), True
venv/lib/python2.7/site-packages/docker/api/client.py:228: in _result
    self._raise_for_status(response)
venv/lib/python2.7/site-packages/docker/api/client.py:224: in _raise_for_status
    raise create_api_error_from_http_exception(e)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

e = HTTPError(u'500 Server Error: Internal Server Error for url: http+docker://localunixsocket/v1.30/services/create',)

    def create_api_error_from_http_exception(e):
        """
        Create a suitable APIError from requests.exceptions.HTTPError.
        """
        response = e.response
        try:
            explanation = response.json()['message']
        except ValueError:
            explanation = (response.content or '').strip()
        cls = APIError
        if response.status_code == 404:
            if explanation and ('No such image' in str(explanation) or
                                'not found: does not exist or no pull access'
                                in str(explanation) or
                                'repository does not exist' in str(explanation)):
                cls = ImageNotFound
            else:
                cls = NotFound
>       raise cls(e, response=response, explanation=explanation)
E       TypeError: 'exceptions.ValueError' object is not callable

venv/lib/python2.7/site-packages/docker/errors.py:31: TypeError
```

**Comment by shin-** [comment] 2017-12-14 20:36
@mbovo Thanks for the follow-up! Would you be able to share the snippet of code you're executing leading up to this error?

**Comment by mbovo** [comment] 2017-12-18 11:08
@shin-  The code involved (simplified but still failing) is a function served as api rest using Flask
```
def deploy(self, data):
        client = docker.from_env()
        service = client.services.create("redis:4.0.1 - alpine", name='redis')
        return json.dumps(service.attrs)
```
Full trace:

```
(venv) pytest ./tests/test_api.py 
=============================================================================== test session starts ================================================================================
platform darwin -- Python 2.7.13, pytest-3.3.1, py-1.5.2, pluggy-0.6.0
rootdir: /Users/mbovo/fworks/devops/gindrop, inifile: setup.cfg
plugins: xdist-1.20.1, pep8-1.0.6, forked-0.2, cov-2.5.1
collected 8 items                                                                                                                                                                  

tests/test_api.py .......F                                                                                                                                                   [100%]

===================================================================================== FAILURES =====================================================================================
___________________________________________________________________________________ test_deploy ____________________________________________________________________________________

    def test_deploy():
    
        filename = os.path.join(os.path.dirname(__file__), 'files', 'deploy.yml')
        with file(filename) as f:
            deploy = f.read()
        data = dict(
            file=(io.BytesIO(deploy), "deploy.yml"),
        )
>       response = client.put('/deploy/deploy_pytest', content_type='multipart/form-data', data=data)

tests/test_api.py:77: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
venv/lib/python2.7/site-packages/werkzeug/test.py:811: in put
    return self.open(*args, **kw)
venv/lib/python2.7/site-packages/flask/testing.py:127: in open
    follow_redirects=follow_redirects)
venv/lib/python2.7/site-packages/werkzeug/test.py:764: in open
    response = self.run_wsgi_app(environ, buffered=buffered)
venv/lib/python2.7/site-packages/werkzeug/test.py:677: in run_wsgi_app
    rv = run_wsgi_app(self.application, environ, buffered=buffered)
venv/lib/python2.7/site-packages/werkzeug/test.py:884: in run_wsgi_app
    app_rv = app(environ, start_response)
venv/lib/python2.7/site-packages/flask/app.py:1997: in __call__
    return self.wsgi_app(environ, start_response)
venv/lib/python2.7/site-packages/flask/app.py:1985: in wsgi_app
    response = self.handle_exception(e)
venv/lib/python2.7/site-packages/flask/app.py:1540: in handle_exception
    reraise(exc_type, exc_value, tb)
venv/lib/python2.7/site-packages/flask/app.py:1982: in wsgi_app
    response = self.full_dispatch_request()
venv/lib/python2.7/site-packages/flask/app.py:1614: in full_dispatch_request
    rv = self.handle_user_exception(e)
venv/lib/python2.7/site-packages/flask/app.py:1517: in handle_user_exception
    reraise(exc_type, exc_value, tb)
venv/lib/python2.7/site-packages/flask/app.py:1612: in full_dispatch_request
    rv = self.dispatch_request()
venv/lib/python2.7/site-packages/flask/app.py:1598: in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
gindrop/api.py:186: in do_deploy
    jdata = manager.deploy(data)
gindrop/swarm.py:78: in deploy
    service = client.services.create("redis:4.0.1 - alpine",name='redis')
venv/lib/python2.7/site-packages/docker/models/services.py:177: in create
    service_id = self.client.api.create_service(**create_kwargs)
venv/lib/python2.7/site-packages/docker/utils/decorators.py:34: in wrapper
    return f(self, *args, **kwargs)
venv/lib/python2.7/site-packages/docker/api/service.py:134: in create_service
    self._post_json(url, data=data, headers=headers), True
venv/lib/python2.7/site-packages/docker/api/client.py:228: in _result
    self._raise_for_status(response)
venv/lib/python2.7/site-packages/docker/api/client.py:224: in _raise_for_status
    raise create_api_error_from_http_exception(e)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

e = HTTPError(u'400 Client Error: Bad Request for url: http+docker://localunixsocket/v1.30/services/create',)

    def create_api_error_from_http_exception(e):
        """
        Create a suitable APIError from requests.exceptions.HTTPError.
        """
        response = e.response
        try:
            explanation = response.json()['message']
        except ValueError:
            explanation = (response.content or '').strip()
        cls = APIError
        if response.status_code == 404:
            if explanation and ('No such image' in str(explanation) or
                                'not found: does not exist or no pull access'
                                in str(explanation) or
                                'repository does not exist' in str(explanation)):
                cls = ImageNotFound
            else:
                cls = NotFound
>       raise cls(e, response=response, explanation=explanation)
E       TypeError: 'exceptions.ValueError' object is not callable

venv/lib/python2.7/site-packages/docker/errors.py:31: TypeError
------------------------------------------------------------------------------- Captured stderr call -------------------------------------------------------------------------------
2017-12-18 12:01:05,665 | 11994 |[MainThread] |     DEBUG | docker.auth:find_config_file() | Trying paths: ['/Users/mbovo/.docker/config.json', '/Users/mbovo/.dockercfg']
2017-12-18 12:01:05,666 | 11994 |[MainThread] |     DEBUG | docker.auth:find_config_file() | Found file at path: /Users/mbovo/.docker/config.json
2017-12-18 12:01:05,666 | 11994 |[MainThread] |     DEBUG | docker.auth:load_config() | Found 'auths' section
2017-12-18 12:01:05,666 | 11994 |[MainThread] |     DEBUG | docker.auth:parse_auth() | Found entry (registry=u'docker.facilitylive.int', username=u'mbovo')
2017-12-18 12:01:05,666 | 11994 |[MainThread] |     DEBUG | docker.auth:load_config() | Found 'HttpHeaders' section
2017-12-18 12:01:05,666 | 11994 |[MainThread] |     DEBUG | docker.auth:get_config_header() | Looking for auth config
2017-12-18 12:01:05,666 | 11994 |[MainThread] |     DEBUG | docker.auth:resolve_authconfig() | Looking for auth entry for 'docker.io'
2017-12-18 12:01:05,666 | 11994 |[MainThread] |     DEBUG | docker.auth:resolve_authconfig() | No entry found
2017-12-18 12:01:05,666 | 11994 |[MainThread] |     DEBUG | docker.auth:get_config_header() | No auth config found
2017-12-18 12:01:05,671 | 11994 |[MainThread] |     DEBUG | urllib3.connectionpool:_make_request() | http://localhost:None "POST /v1.30/services/create HTTP/1.1" 400 125
-------------------------------------------------------------------------------- Captured log call ---------------------------------------------------------------------------------
auth.py                    234 DEBUG    Trying paths: ['/Users/mbovo/.docker/config.json', '/Users/mbovo/.dockercfg']
auth.py                    238 DEBUG    Found file at path: /Users/mbovo/.docker/config.json
auth.py                    282 DEBUG    Found 'auths' section
auth.py                    214 DEBUG    Found entry (registry=u'docker.facilitylive.int', username=u'mbovo')
auth.py                    285 DEBUG    Found 'HttpHeaders' section
auth.py                     44 DEBUG    Looking for auth config
auth.py                    102 DEBUG    Looking for auth entry for 'docker.io'
auth.py                    113 DEBUG    No entry found
auth.py                     59 DEBUG    No auth config found
connectionpool.py          396 DEBUG    http://localhost:None "POST /v1.30/services/create HTTP/1.1" 400 125
======================================================================== 1 failed, 7 passed in 0.55 seconds ========================================================================
(venv) docker images
REPOSITORY                              TAG                 IMAGE ID            CREATED             SIZE
sonatype/nexus3                         latest              ee8a3baf060c        2 weeks ago         474MB
redis                                   4.0.1-alpine        d8b7cc942736        3 months ago        27.5MB
docker.facilitylive.int/custom_centos   7.4.1708            1f2cdc055c5f        3 months ago        269MB
(venv) docker services
docker: 'services' is not a docker command.
See 'docker --help'
(venv) docker service ls
ID                  NAME                MODE                REPLICAS            IMAGE               PORTS
(venv) 
```

The expected result is failure with something more clear about what's going wrong on docker engine side but the only thing retrieved is the `TypeError: 'exceptions.ValueError' object is not callable`

Thanks in advance

**Comment by shin-** [comment] 2017-12-18 19:35
Thanks! I'll look into it asap

**Comment by feliperuhland** [comment] 2017-12-18 22:28
Hello, I tried to reproduce the exception, but I did not succeed.

```
docker (2.6.1)
docker-pycreds (0.2.1)
requests (2.18.4)
```

```
Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:39:28 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:45:38 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

```
Python 2.7.13 (default, Apr 20 2017, 12:13:37) 
[GCC 6.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import docker
>>> client = docker.from_env()
>>> service = client.services.create("redis:4.0.1 - alpine", name='redis')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/docker/models/services.py", line 177, in create
    service_id = self.client.api.create_service(**create_kwargs)
  File "/usr/lib/python2.7/site-packages/docker/utils/decorators.py", line 34, in wrapper
    return f(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/docker/api/service.py", line 134, in create_service
    self._post_json(url, data=data, headers=headers), True
  File "/usr/lib/python2.7/site-packages/docker/api/client.py", line 228, in _result
    self._raise_for_status(response)
  File "/usr/lib/python2.7/site-packages/docker/api/client.py", line 224, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/usr/lib/python2.7/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.APIError: 400 Client Error: Bad Request ("rpc error: code = InvalidArgument desc = ContainerSpec: "redis:4.0.1 - alpine" is not a valid repository/tag")
```

**Comment by shin-** [comment] 2017-12-19 00:57
@mbovo I can't reproduce either, even inserting that snippet into a basic Flask app doesn't recreate the error for me. It's probably an issue with your app or your environment. Are you or a library you're using monkey-patching the builtin exceptions?

**Comment by feliperuhland** [comment] 2017-12-20 15:09
@mbovo can you try running this code in Python console?

```python
>>> import docker
>>> client = docker.from_env()
>>> service = client.services.create("redis:4.0.1 - alpine", name='redis')
```

**Comment by mbovo** [comment] 2017-12-24 16:59
@feliperuhland sorry for the delay, 
from the python console all is working as expected:
```
Python 2.7.13 (default, Jul 18 2017, 09:16:53) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import docker
>>> client = docker.from_env()
>>> client.services.create('redis:4.0.1 - alpine', name='redis')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mbovo/fworks/devops/gindrop/venv/lib/python2.7/site-packages/docker/models/services.py", line 177, in create
    service_id = self.client.api.create_service(**create_kwargs)
  File "/Users/mbovo/fworks/devops/gindrop/venv/lib/python2.7/site-packages/docker/utils/decorators.py", line 34, in wrapper
    return f(self, *args, **kwargs)
  File "/Users/mbovo/fworks/devops/gindrop/venv/lib/python2.7/site-packages/docker/api/service.py", line 134, in create_service
    self._post_json(url, data=data, headers=headers), True
  File "/Users/mbovo/fworks/devops/gindrop/venv/lib/python2.7/site-packages/docker/api/client.py", line 228, in _result
    self._raise_for_status(response)
  File "/Users/mbovo/fworks/devops/gindrop/venv/lib/python2.7/site-packages/docker/api/client.py", line 224, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/Users/mbovo/fworks/devops/gindrop/venv/lib/python2.7/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.APIError: 400 Client Error: Bad Request ("rpc error: code = InvalidArgument desc = ContainerSpec: "redis:4.0.1 - alpine" is not a valid repository/tag")
>>> 
```
So it seems not a library bug 👍 
Using the lib wrapped around Flask is working too.
I'm investigating further... the problem is limited to pytest + Flask test_client:

```
app = Flask(__name__)
appclient = app.test_client()
response = appclient.put('/deploy/deploy_test', content_type='multipart/form-data', data=data)

```
returns the well known
`E       TypeError: 'exceptions.ValueError' object is not callable`

Seems the library docker/errors.py:22 
`cls = APIError`

can't found the correct APIError class when using pytest + Flask test_client()

Thanks again for your support!

**Comment by feliperuhland** [comment] 2018-01-03 22:47
@shin- I think we can close this.

**Closed** 2018-01-24 01:28 UTC
Labels: kind/question
